### PR TITLE
Added the new config since kibana 4.2.x, support for custom log file and server.basePath

### LINKED ISSUE #78: Support for server.basePath
server.basePath configuration is introduced, it should be nice for this module!

### PR DESCRIPTION
**Pull request by caskolkm**
Since kibana 4.2.x they changed the syntax for the config file. An other feature is the server.basePath which allows you to add a root context path. This will fix #78

### CODE REVIEW

**Comment by caskolkm** [comment]
This will fix #78

**Comment by caskolkm** [comment]
@jlambert121 can you review this?

**Comment by jlambert121** [comment]
This looks great, thanks!  Could you add some tests around the version selection?

**Comment by caskolkm** [comment]
@jlambert121 mmm, it is the first time that i need to write a test for puppet code. Can you explain how i should write a test?

**Comment by caskolkm** [comment]
@jlambert121 thnx, i added some tests, hope you like it!

**Comment by jlambert121** [comment]
Thanks!

**Comment by caskolkm** [comment]
Thnx, can you release a new version of this module?

**Comment by jlambert121** [comment]
2.5.0 pushed

**Pull request merged**
