### PR TITLE
add plugin support

### PR DESCRIPTION
**Pull request by bilsch**
hiera config to add / remove plugins also works

kibana::plugins:
  marvel:
    source: elasticsearch/marvel/latest

And to remove

kibana::plugins:
  marvel:
    source: elasticsearch/marvel/latest
    ensure: absent

### CODE REVIEW

**Comment by bilsch** [comment]
I'll work on getting the test suites added for this shortly

**Comment by bilsch** [comment]
This should be ready for review. Let me know if you want more test cases added in

**Comment by bilsch** [comment]
@jlambert121 mind taking a look at this?

**Comment by jlambert121** [comment]
This looks great - thanks!  Would you add a test for removing a plugin and squish things down to a single commit and I'll merge it?

**Comment by bilsch** [comment]
@jlambert121 ok tweaked the rspec tests and added the remove / absent test.

**Comment by jlambert121** [comment]
Thanks!

**Pull request merged**
